spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
        page-parameter: page

logging:
  level:
    org.hibernate.SQL: debug

---

spring:
  config.activate.on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lecture-management
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  config.activate.on-profile: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lecture-management-test
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create
